#!/bin/bash

set -x

cargo build -r

time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -s Delphi -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -s Delphi -s "Glimmerdrift Reaches" -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -s Delphi -s "Glimmerdrift Reaches" -s Daibei -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -f sector_lists/Ju.txt -vvv
