#!/bin/bash

set -x

cargo build -r

time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -s Delphi -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -s Delphi -s "Glimmerdrift Reaches" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -s 'Spinward Marches' -s Deneb -s Gvurrdon -s Tuglikki -s Provence -s Corridor -s Windhorn -s Vland -s Meshan -s Lishun -s 'Trojan Reach' -s Reft -s Gushemege -s Dagudashaag -s Core -s "Riftspan Reaches" -s "Verge" -s "Ilelish" -s "Zarushagar" -s Massilia -s Antares -s "Empty Quarter" -s Fornast -s Ley -s Delphi -s "Glimmerdrift Reaches" -s Daibei -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -f sector_lists/Ju.txt -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -f sector_lists/Ju.txt -s Amderstun -s Astron -s Banners -s Datsatl -s "Faoheiroi'iyhao" -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -f sector_lists/Ju.txt -s Amderstun -s Astron -s Banners -s Datsatl -s "Faoheiroi'iyhao" -s Finggvakhou -s Hadji -s Hanstone -s Ianshaplzdier -s Katoonah -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/Im.txt -f sector_lists/CsIm.txt -f sector_lists/V.txt -f sector_lists/Zh.txt -f sector_lists/As.txt -f sector_lists/So.txt -f sector_lists/K.txt -f sector_lists/CsTw.txt -f sector_lists/Hv.txt -f sector_lists/Ju.txt -s Amderstun -s Astron -s Banners -s Datsatl -s "Faoheiroi'iyhao" -s Finggvakhou -s Hadji -s Hanstone -s Ianshaplzdier -s Katoonah -s Khaeaw -s Leonidae -s Malorn -s Ngathksirz -s Rfigh -i -vvv
time target/release/traderust -d /var/tmp/traderust/ -o /var/tmp/traderust_output -f sector_lists/all.txt -i -vvv
